[project]
name = "clenow-momentum-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "yfinance",
    "requests",
    "beautifulsoup4",
]
